title: Magpie Opera Collective
url: "https://jager-kujawa.com"
baseurl: "/magpie-opera-collective"
theme: minima
collections:
  artists:
    output: true
  events:
    output: true
artist_categories:
 - Soprani
 - Mezzo-Soprani
 - Tenors
 - Baritones
 - Accompanist