title: Magpie Opera Collective
url: "https://magpieopera.org"
baseurl: "/"
theme: minima
collections:
  artists:
    output: true
  events:
    output: true
artist_categories:
 - Soprani
 - Mezzo-Soprani
 - Tenors
 - Baritones
 - Accompanist