title: Magpie Opera Collective
url: "https://magpieopera.org"
theme: minima
future: true
collections:
  artists:
    output: true
  events:
    output: true
    permalink: /:collection/:name
artist_categories:
 - Soprani
 - Mezzo-Soprani
 - Tenors
 - Baritones
 - Accompanist
socials:
  - link: https://www.instagram.com/magpieoperacollective/
    title: Instagram
    icon: fa-brands fa-instagram
  - link: https://www.youtube.com/channel/UCGuMQmoHRKFLEjaZL7BmKPg
    title: YouTube
    icon: fa-brands fa-youtube
  - link: mailto:magpieoperacollective@gmail.com
    title: Email Us
    icon: fa-solid fa-envelope