title: Magpie Opera Collective
# TODO: Remove this once a custom domain is configured
baseurl: "/magpie-opera-collective"
theme: minima
collections:
  artists:
    output: true
  events:
    output: true
